


# ------------------------------------------------------ #
#                         Comment                        #
# ------------------------------------------------------ #

















# ------------------------------------------------------ #
#                         Post                           #
# ------------------------------------------------------ #

# Create Post 
###
POST http://localhost:5000/api/posts HTTP/1.1 
content-type: application/json 

{ 
    "title": "adcg hy fgfgtfyt kjh?", 
    "body": "qrstuv wxyz ghijk abcdef lmnop.", 
    "author": "Rijwan Hossain"
} 


// Get All Post
###
GET http://localhost:5000/api/posts HTTP/1.1


// Get Single Post
###
GET http://localhost:5000/api/posts/5c9e989c771e480dc8979234 HTTP/1.1


// Update Post
###
PATCH http://localhost:5000/api/posts/5c9e989c771e480dc8979234 HTTP/1.1 
content-type: application/json 

{ 
    "title": "adcg hy fgfgtfyt kjh?", 
    "body": "abcdef ghijk lmnop qrstuv wxyz.", 
    "author": "Rijwan Hossain"
} 


// Delete Post
###
DELETE http://localhost:5000/api/posts/5ca0ebb60f7f8e0c408c470f HTTP/1.1










# ------------------------------------------------------ #
#                       Tutorial                         #
# ------------------------------------------------------ #


###
// Create Tutorial
POST http://localhost:5000/api/tutorials HTTP/1.1
content-type: application/json

{ 
    "question": "How to remove belly fat", 
    "solution": "qrstuv wxyz ghijk abcdef lmnop."
} 


###
// Get All Tutorial
GET http://localhost:5000/api/tutorials HTTP/1.1


###
// Get single Tutorial
GET http://localhost:5000/api/tutorials/5c9de113128e870604a41dcf HTTP/1.1


### 
// Update Tutorial
PATCH http://localhost:5000/api/tutorials/5c9e729a1a90972320276b8b HTTP/1.1
content-type: application/json

{ 
    "question": "How fat stored in belly", 
    "solution": "abcdef ghijk lmnop qrstu vwxyz."
} 



###
// Delete Tutorial 
DELETE http://localhost:5000/api/tutorials/5c9de113128e870604a41dcf HTTP/1.1












# ------------------------------------------------------ #
#                         User                           #
# ------------------------------------------------------ #

// Create ID
POST http://localhost:5000/api/users/register HTTP/1.1
content-type: application/json

{ 
    "name": "Rijwan Hossain", 
    "email": "rijwan.cse@gmail.com", 
    "password": "152002007", 
    "confirmPassword": "152002007" 
} 


// Show All User
###

GET http://localhost:5000/api/users/alluser HTTP/1.1 


// Login
### 

POST http://localhost:5000/api/users/login HTTP/1.1
content-type: application/json

{ 
    "email": "rijwan.152.cse@gmail.com", 
    "password": "152002007" 
} 



// Get single user
###

GET http://localhost:5000/api/users/register/5c99ed6f7211e71758287865 HTTP/1.1 


// Update User
###

PATCH http://localhost:5000/api/users/register/5c96eaf26a163421c4bf4b6a HTTP/1.1 
content-type: application/json

{ 
    "weight": "72 KG", 
    "gender": "male",
    "height": "5 ft 10 inch", 
    "mobile": "01758712370",
    "address": "Mirpur-Dhaka, Bangladesh in South-Asia"
} 


// Delete User
###

DELETE http://localhost:5000/api/users/register/5c9aaa64eb1be60d981db9e0 HTTP/1.1 

